const FETCH_TASK_LOADING = 'FETCH_TASK_LOADING';
const FETCH_TASK_ERROR = 'FETCH_TASK_ERROR';
const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';

export { FETCH_TASK_LOADING, FETCH_TASK_ERROR, FETCH_TASK_SUCCESS };
